FORMAT: 1A
HOST: https://mediaops.viacom.com/

# Media Services API

Media services API provides a way to do the following

+ Convert from one media format to another.
+ Extract info about the media (both video and image) such as duration , height , width , format etc.
+ Mgid to http url and absolute path conversion.
+ GSP directory listing.

# Scenarist Closed Captions (SCC) to Timed Text (TT) Conversion API

A simple API to convert .scc file(s) to .dfxp file(s). To call this service, send a request JSON (sample given below). On success, the service responds with a status code 201 with the status message, error code and time taken in milliseconds. 

# Convert [/scctott]
### Create a SCC to TT Conversion Request [POST]
Request a new Conversion.

    + Headers
    
        Accept-Charset:utf-8
        Connection:keep-alive
        Accept: application/json
        Authorization:Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Request (application/json)
    + Headers
        
            Accept-Charset: utf-8
            Connection: keep-alive
            Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

    + Attributes
        + client (string, required) - The client id sending the request.
        + assets (array, required) - Array of objects containing sourceUri and destinationUri.
            + (object, required)
                + sourceUri (string, required)
                + destinationUri (string, required)
                + *additionalFields/keyValuePairs* (array) Array of objects containing additional keys
                    + (object)
                        + key - the key
                        + value - the value

    + Body
    
            {
                "client": "mediabus_app",
                "assets": [
                    {
                        "sourceUri": "/GSPstor/mtvnteststor/alias/testenv2/3393886_273794_20130918011313133.SCC",
                        "destinationUri": "dest",
                        "additionalFields" : [
                            {
                                "key": "offset",
                                "value": "111"
                            },
                            {
                                "key": "needsPhaseSupport",
                                "value": true
                            },
                            {
                                "key": "timedTextFileName",
                                "value": "timedText.dfxp"
                            }
                        ]
                    }
                ]
            }

+ Response 201
    + Headers
        
            Content-Type: application/json; utf-8

    + Body

            {
                "message": "Ok",
                "errorCode": 0,
                "timeTakenInMillis": 1438372393894
                "submittedAt": "2015-03-28T13:26:37-04:00",
                "completedAt": "2011-03-24T11:45:47-04:00",
            }

+ Response 401
    + Headers
        
            Content-Type: application/json; utf-8

    + Body
    
            {
                "message": "Unauthorized",
                "errorCode": 0,
                "timeTakenInMillis": 1438372393894
                "submittedAt": "2015-03-28T13:26:37-04:00",
                "completedAt": "2011-03-24T11:45:47-04:00",
            }
            
+ Response 403
    + Headers
        
            Content-Type: application/json; utf-8

    + Body
    
            {
                "message": "Forbidden",
                "errorCode": 0,
                "timeTakenInMillis": 1438372393894
                "submittedAt": "2015-03-28T13:26:37-04:00",
                "completedAt": "2011-03-24T11:45:47-04:00",
            }

+ Response 404
    + Headers
        
            Content-Type: application/json; utf-8

    + Body
    
            {
                "message": "Not Found",
                "errorCode": 0,
                "timeTakenInMillis": 1438372393894
                "submittedAt": "2015-03-28T13:26:37-04:00",
                "completedAt": "2011-03-24T11:45:47-04:00",
            }
            
+ Response 500
    + Headers
        
            Content-Type: application/json; utf-8

    + Body
    
            {
                "message": "Internal Server Error",
                "errorCode": 0,
                "timeTakenInMillis": 1438372393894
                "submittedAt": "2015-03-28T13:26:37-04:00",
                "completedAt": "2011-03-24T11:45:47-04:00",
            }
        
+ Response 504
    + Headers
        
            Content-Type: application/json; utf-8

    + Body
    
            {
                "message": "Gateway Timeout",
                "errorCode": 0,
                "timeTakenInMillis": 1438372393894
                "submittedAt": "2015-03-28T13:26:37-04:00",
                "completedAt": "2011-03-24T11:45:47-04:00",
            }
        
